import { useEffect, useState } from "react";
import {
  Activity,
  ShieldCheck,
  AlertTriangle,
  TrendingUp,
  Search,
  RefreshCw,
} from "lucide-react";
import { getRiskPredictions } from "../api";

function RiskAnalysis() {
  const [predictions, setPredictions] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    loadRiskPredictions();
  }, []);

  async function loadRiskPredictions() {
    try {
      setLoading(true);
      setError("");

      const data = await getRiskPredictions();
      setPredictions(data);
    } catch (err) {
      console.error(err);
      setError("Unable to load risk assessments.");
    } finally {
      setLoading(false);
    }
  }

  const lowRisk = predictions.filter(
    (item) => item.risk_category === "Low"
  ).length;

  const moderateRisk = predictions.filter(
    (item) => item.risk_category === "Moderate"
  ).length;

  const elevatedRisk = predictions.filter(
    (item) => item.risk_category === "Elevated"
  ).length;

  const filteredPredictions = predictions.filter((item) =>
    String(item.patient_id)
      .toLowerCase()
      .includes(searchTerm.toLowerCase())
  );

  function getRiskClass(category) {
    if (category === "Low") return "risk-badge low";
    if (category === "Moderate") return "risk-badge moderate";
    return "risk-badge elevated";
  }

  function formatProbability(probability) {
  return `${Number(probability).toFixed(1)}%`;
}

  function formatDate(dateString) {
    if (!dateString) return "—";

    return new Date(dateString).toLocaleString("en-IN", {
      dateStyle: "medium",
      timeStyle: "short",
    });
  }

  return (
    <div className="dashboard-content">
      <div className="page-header-row">
        <div>
          <h2>Risk Analysis</h2>
          <p>
            Review cardiovascular risk assessments generated by the trained
            machine learning model.
          </p>
        </div>

        <button
          className="secondary-btn"
          onClick={loadRiskPredictions}
          disabled={loading}
        >
          <RefreshCw size={16} />
          Refresh
        </button>
      </div>

      <div className="patient-summary-grid risk-summary-grid">
        <div className="summary-card">
          <div className="summary-icon blue">
            <Activity size={20} />
          </div>

          <div>
            <span>Total Assessments</span>
            <strong>{predictions.length}</strong>
          </div>
        </div>

        <div className="summary-card">
          <div className="summary-icon green">
            <ShieldCheck size={20} />
          </div>

          <div>
            <span>Low Risk</span>
            <strong>{lowRisk}</strong>
          </div>
        </div>

        <div className="summary-card">
          <div className="summary-icon orange">
            <AlertTriangle size={20} />
          </div>

          <div>
            <span>Elevated Risk</span>
            <strong>{elevatedRisk}</strong>
          </div>
        </div>
      </div>

      <section className="panel patients-page-panel">
        <div className="patients-toolbar">
          <div>
            <h3>Risk Assessment History</h3>
            <p>
              Stored cardiovascular risk predictions from the database.
            </p>
          </div>

          <div className="patient-search">
            <Search size={17} />

            <input
              type="text"
              placeholder="Search by patient ID..."
              value={searchTerm}
              onChange={(event) => setSearchTerm(event.target.value)}
            />
          </div>
        </div>

        {loading && (
          <div className="loading-state">
            Loading risk assessments...
          </div>
        )}

        {error && (
          <div className="error-state">
            {error}
          </div>
        )}

        {!loading && !error && (
          <div className="full-patient-table risk-table">
            <div className="full-table-row full-table-heading">
              <span>Patient ID</span>
              <span>Risk Probability</span>
              <span>Risk Category</span>
              <span>Model</span>
              <span>Assessment Date</span>
            </div>

            {filteredPredictions.length === 0 ? (
              <div className="empty-state">
                No risk assessments found.
              </div>
            ) : (
              filteredPredictions.map((prediction) => (
                <div
                  className="full-table-row"
                  key={prediction.id}
                >
                  <span className="patient-id-cell">
  {prediction.patient_id ? `#${prediction.patient_id}` : "—"}
</span>

                  <strong>
                    {formatProbability(prediction.risk_probability)}
                  </strong>

                  <span>
                    <span className={getRiskClass(prediction.risk_category)}>
                      {prediction.risk_category}
                    </span>
                  </span>

                  <span>
                    {prediction.model_name || "—"}
                  </span>

                  <span>
                    {formatDate(prediction.created_at)}
                  </span>
                </div>
              ))
            )}
          </div>
        )}
      </section>

      <section className="panel risk-info-panel">
        <div className="risk-info-icon">
          <TrendingUp size={20} />
        </div>

        <div>
          <h3>About Risk Scores</h3>
          <p>
            The displayed probability is produced by the project's trained
            cardiovascular risk model. Risk categories are derived from the
            project's configured probability thresholds and are intended for
            educational and portfolio demonstration purposes.
          </p>
        </div>
      </section>
    </div>
  );
}

export default RiskAnalysis;